/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n  color: #369; \n  font-family: Arial, Helvetica, sans-serif;   \n  font-size: 250%;\n}\nh2[_ngcontent-%COMP%], h3[_ngcontent-%COMP%] { \n  color: #444;\n  font-family: Arial, Helvetica, sans-serif;   \n  font-weight: lighter;\n}\nbody[_ngcontent-%COMP%] { \n  margin: 2em; \n}\nbody[_ngcontent-%COMP%], input[text][_ngcontent-%COMP%], button[_ngcontent-%COMP%] { \n  color: #888; \n  font-family: Cambria, Georgia; \n}\n\n\n*[_ngcontent-%COMP%] { \n  font-family: Arial, Helvetica, sans-serif; \n}'];