/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './hero-search.service';
import * as import2 from './hero-search.component';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from './hero-search.component.css.shim';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/common/src/pipes/async_pipe';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
  const nodeDebugInfos_HeroSearchComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([
    import1.HeroSearchService,
    import2.HeroSearchComponent
  ]
,import2.HeroSearchComponent,{})];
var renderType_HeroSearchComponent_Host:import3.RenderComponentType = (null as any);
class _View_HeroSearchComponent_Host0 extends import4.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _HeroSearchService_0_4:import1.HeroSearchService;
  _HeroSearchComponent_0_5:import2.HeroSearchComponent;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_HeroSearchComponent_Host0,renderType_HeroSearchComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HeroSearchComponent_Host0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hero-search',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroSearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroSearchService_0_4 = new import1.HeroSearchService(this.parentInjector.get(import10.Http));
    this._HeroSearchComponent_0_5 = new import2.HeroSearchComponent(this._HeroSearchService_0_4,this.parentInjector.get(import11.Router));
    this._appEl_0.initComponent(this._HeroSearchComponent_0_5,([] as any[]),compView_0);
    compView_0.create(this._HeroSearchComponent_0_5,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.HeroSearchService) && (0 === requestNodeIndex))) { return this._HeroSearchService_0_4; }
    if (((token === import2.HeroSearchComponent) && (0 === requestNodeIndex))) { return this._HeroSearchComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroSearchComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroSearchComponent_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<any> {
  if ((renderType_HeroSearchComponent_Host === (null as any))) { (renderType_HeroSearchComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HeroSearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroSearchComponentNgFactory:import13.ComponentFactory<import2.HeroSearchComponent> = new import13.ComponentFactory<import2.HeroSearchComponent>('hero-search',viewFactory_HeroSearchComponent_Host0,import2.HeroSearchComponent);
const styles_HeroSearchComponent:any[] = [import14.styles];
const nodeDebugInfos_HeroSearchComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{searchBox: (null as any)}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import15.TemplateRef,
    import16.NgFor
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_HeroSearchComponent:import3.RenderComponentType = (null as any);
class _View_HeroSearchComponent0 extends import4.DebugAppView<import2.HeroSearchComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import5.AppElement;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import16.NgFor;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _pipe_async_0:import17.AsyncPipe;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_HeroSearchComponent0,renderType_HeroSearchComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HeroSearchComponent0);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',this.debug(1,1,2));
    this.renderer.setElementAttribute(this._el_1,'id','search-component');
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',this.debug(2,1,29));
    this._el_3 = this.renderer.createElement(this._el_1,'h4',this.debug(3,2,4));
    this._text_4 = this.renderer.createText(this._el_3,'Hero Search',this.debug(4,2,8));
    this._text_5 = this.renderer.createText(this._el_1,'\n    ',this.debug(5,2,24));
    this._el_6 = this.renderer.createElement(this._el_1,'input',this.debug(6,3,4));
    this.renderer.setElementAttribute(this._el_6,'id','search-box');
    this._text_7 = this.renderer.createText(this._el_1,'\n    ',this.debug(7,3,74));
    this._el_8 = this.renderer.createElement(this._el_1,'div',this.debug(8,4,4));
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',this.debug(9,4,9));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_8,this.debug(10,5,6));
    this._appEl_10 = new import5.AppElement(10,8,this,this._anchor_10);
    this._TemplateRef_10_5 = new import15.TemplateRef_(this._appEl_10,viewFactory_HeroSearchComponent1);
    this._NgFor_10_6 = new import16.NgFor(this._appEl_10.vcRef,this._TemplateRef_10_5,this.parentInjector.get(import18.IterableDiffers),this.ref);
    this._text_11 = this.renderer.createText(this._el_8,'\n    ',this.debug(11,8,12));
    this._text_12 = this.renderer.createText(this._el_1,'\n  ',this.debug(12,9,10));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(13,10,8));
    var disposable_0:Function = this.renderer.listen(this._el_6,'keyup',this.eventHandler(this._handle_keyup_6_0.bind(this)));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_async_0 = new import17.AsyncPipe(this.ref);
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import16.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import9.SimpleChange} = (null as any);
    const valUnwrapper:any = new import9.ValueUnwrapper();
    this.debug(10,5,6);
    changes = (null as any);
    this.debug(10,5,11);
    valUnwrapper.reset();
    const currVal_1:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.heroes));
    if ((valUnwrapper.hasWrappedValue || import6.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this._NgFor_10_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import9.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_10_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_10_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(10,5,6);
    this._pipe_async_0.ngOnDestroy();
  }
  private _handle_keyup_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(6,3,38);
    const pd_0:any = ((<any>this.context.search(this._el_6.value)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeroSearchComponent0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<import2.HeroSearchComponent> {
  if ((renderType_HeroSearchComponent === (null as any))) { (renderType_HeroSearchComponent = viewUtils.createRenderComponentType('/Users/albatrosary/Hands-on/HeroEditor/src/components/hero-search/hero-search.component.ts class HeroSearchComponent - inline template',0,import12.ViewEncapsulation.Emulated,styles_HeroSearchComponent,{})); }
  return new _View_HeroSearchComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_HeroSearchComponent1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import0.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_HeroSearchComponent1 extends import4.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement) {
    super(_View_HeroSearchComponent1,renderType_HeroSearchComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_HeroSearchComponent1);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',this.debug(0,5,6));
    this.renderer.setElementAttribute(this._el_0,'class','search-result');
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,6,60));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import9.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,6,60);
    const currVal_1:any = import6.interpolate(1,'\n        ',this.context.$implicit.name,'\n      ');
    if (import6.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,6,10);
    const pd_0:any = ((<any>this.parent.context.gotoDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeroSearchComponent1(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import5.AppElement):import4.AppView<any> {
  return new _View_HeroSearchComponent1(viewUtils,parentInjector,declarationEl);
}